#!/usr/bin/env sh
if [ -f "$(dirname -- "$0")/_/husky.sh" ]; then
  . "$(dirname -- "$0")/_/husky.sh"
elif [ -f "$(dirname "$0")/_/husky.sh" ]; then
  . "$(dirname "$0")/_/husky.sh"
fi

bunx commitlint --edit "$1" || {
  echo "❌ Commit message does not follow conventional commit format"
  exit 1
}